Repository CM-Well/CM-Well, pull requests merged in 2018-06, with the labels that each got.

#738 prefetch buffer size configurable
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/Downloader.scala
  server/cmwell-dc/src/pack/application.conf
  server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala
  server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManagerSettings.scala
Labels: STP

#765 properly handle old indexer commands in the new indexer
  server/cmwell-bg/src/main/scala/cmwell/bg/IndexerStream.scala
Labels: bug, dcc:comp

#747 Connection pool
  server/cmwell-data-tools/src/main/resources/reference.conf
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/BufferFillerActor.scala
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/DataToolsConfig.scala
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/HttpConnections.scala
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/Retry.scala
  server/cmwell-dc/src/main/resources/reference.conf
  server/cmwell-dc/src/pack/application.conf
Labels: STP, data tools

#772 proper fallback to QUORUM
  server/cmwell-irw/src/main/scala/cmwell/irw/IRWServiceNativeImpl2.scala
Labels: bug

#778 Large File Infoton Duplicates Fix
  server/cmwell-domain/src/main/scala/cmwell/domain/Infoton.scala
Labels: bug

#787 Crawler: disable false alarm for first-time-write-to-path with grouped commands
  server/cmwell-bg/src/main/scala/cmwell/bg/Merger.scala
  server/cmwell-bg/src/main/scala/cmwell/crawler/CrawlerStream.scala
  server/cmwell-bg/src/main/scala/cmwell/crawler/OffsetThrottler.scala
Labels: bug
