Repository CM-Well/CM-Well, pull requests merged in 2018-02, with the labels that each got.

#488 Added Ingest Stats to the STP dashboard #467
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/ingester/Ingester.scala
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/stats/DownloaderStats.scala
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/stats/IngesterStats.scala
  server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/InfotonReporter.scala
  server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala
Labels: STP

#517 remove context check in stream
  server/cmwell-ws/app/controllers/Application.scala
Labels: enhancement

#520 #458 - Show Sensor horizon status on dashboard
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/BufferFillerActor.scala
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/Downloader.scala
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/japi/DownloaderUtils.scala
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/sparql/SparqlProcessor.scala
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/sparql/SparqlTriggeredProcessor.scala
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/stats/DownloaderStats.scala
  server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala
Labels: STP

#528 #443 Added STP source to dashboard and relevant logs
  server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala
Labels: STP

#537 #451 Removed misleading token time from dashboard when none have been persisted
  server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala
Labels: STP

#543 fixed casting error in data tools
  server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/BufferFillerActor.scala
Labels: bug

#527 #514 added STP user / token for _in API call of STP
  server/cmwell-cons/src/main/scala/ComponentConf.scala
  server/cmwell-cons/src/main/scala/DataInitializer.scala
  server/cmwell-sparql-agent/src/main/resources/reference.conf
  server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala
Labels: STP
